[package]
name = "rangeProof"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bulletproofs = "4.0.0"
curve25519-dalek = "3.2.1"
merlin = "3.0.0"
rand = "0.8.5"
